name: test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
  pull_request:

jobs:
  unit-test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        jdk: [8, 17, 19]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.11.1.1347

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Run tests (jdk<17)
        if: ${{ matrix.jdk < 17 }}
        run: |
          clojure -M:test
      - name: Run tests (jdk>=17)
        if: ${{ matrix.jdk >= 17 }}
        run: |
          clojure -M:jdk-${{matrix.jdk}}:test
